<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>dev.whilo</groupId>
    <artifactId>whiloservers-parent</artifactId>
    <version>v1</version>
  </parent>

  <artifactId>whiloservers-velocity</artifactId>
  <packaging>jar</packaging>

  <properties>
    <velocity.api.version>3.5.1</velocity.api.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>com.velocitypowered</groupId>
      <artifactId>velocity-api</artifactId>
      <version>${velocity.api.version}</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.yaml</groupId>
      <artifactId>snakeyaml</artifactId>
      <version>2.2</version>
    </dependency>
  </dependencies>

  <build>
    <finalName>WhiloServers-Velocity-v1</finalName>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.13.0</version>
        <configuration>
          <annotationProcessorPaths>
            <path>
              <groupId>com.velocitypowered</groupId>
              <artifactId>velocity-api</artifactId>
              <version>${velocity.api.version}</version>
            </path>
          </annotationProcessorPaths>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>3.5.1</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <relocations>
                <relocation>
                  <pattern>org.yaml.snakeyaml</pattern>
                  <shadedPattern>dev.whilo.whiloservers.velocity.libs.snakeyaml</shadedPattern>
                </relocation>
              </relocations>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
